---
- hosts: all
  user: dimpy
  become: true
  become_method: sudo
  tasks:
   - name: commenting log conf
     copy:
        src=/home/dimpy/rpc
        dest=/etc/logrotate.d/
        force=yes
        owner=root
        group=root
